AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  redirectMobenga:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://bucket/key
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::917894928836:role/service-role/jj-cloudwatch-lambda-execution-role'

